### ISSUE TITLE
the sentence separator @@ is removed in the provided train and test files

### ISSUE THREAD

**Issue by willanxywc** [minimalparts/nonce2vec#1]
I notice in the code            
```
 for s in fields[1].split("@@"):
     sentences.append(s.split(' '))
```
which means @@ should be in the original train and test corpus, however can't be found here. Is your processed version with sentence separators available? It's necessary for reproduction and further experiments. BTW I don't mean the raw files provided by Lazaridou.

Thanks~

**Comment by minimalparts** [comment]
You're completely right. We had the wrong version of the chimera data in the repo. Apologies for this. I have now uploaded the correct files to the data/chimeras directory. 

Thanks for spotting this!

**Comment by willanxywc** [comment]
Thanks
