### ISSUE TITLE
Crash when no context word is in informativeness model

### ISSUE THREAD

**Issue by bloemj** [minimalparts/nonce2vec#13]
Hi!
I noticed that Nonce2Vec crashes when cwi is used and there is a training sentence for which none of the context words are in the info model vocabulary. In our case this occurred because our info model had a frequency cutoff of 5 and there were some noise sentences containing nothing but a few low-frequency words.

It's fixed by simply returning zero when the info model inference produces no output: https://github.com/bloemj/nonce2vec/commit/3e36389da1113652b645b8e87b8a289cfee67f54

Not sure if that's the best way to fix it as I don't know if that zero is handled well elsewhere in the code, but it stops the crash.

**Comment by akb89** [comment]
Ok. LGTM, though I'd prefer to return an empty list in _get_prb_distrib to remain consistent. Will fix it now.
