### ISSUE TITLE
hi~which version of wikipedia corpus was used?

### ISSUE THREAD

**Issue by willanxywc** [minimalparts/nonce2vec#2]
Which version of wikipedia corpus do you use to pre-train the N2V?  It's not clearly stated in the paper but there are so many versions or copies wikipedia available.

**Comment by minimalparts** [comment]
We used a rather old dump from November 2015, which we had lying around already pre-processed. I don't think there should be too much variation across dumps, but if you really want to replicate everything from scratch, I think I still have the tokenised sentences somewhere and could get them to you (contact me offline). Also, the gensim model we trained is available [here](http://clic.cimec.unitn.it/~aurelie.herbelot/wiki_all.model.tar.gz).

**Comment by willanxywc** [comment]
Thanks~
